---
driver:
  name: docker
  socket: <%= ENV['DOCKER_HOST'] %>

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu
  - name: centos

suites:
  - name: default
    run_list:
      - recipe[automake]
  - name: version
    run_list:
      - recipe[automake]
    attributes:
      automake:
        version: 1.4
  - name: preifx
    run_list:
      - recipe[automake]
    attributes:
      automake:
        prefix: "/opt/local"
