name             'automake'
maintainer       'Rudolph Miller'
maintainer_email 'chopsticks.tk.ppfm@gmail.com'
license          'MIT'
description      'Installs/Configures automake'
long_description 'Installs/Configures automake'
version          '0.1.0'
